// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bydjqnetcjgzplbgbhne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5ZGpxbmV0Y2pnenBsYmdiaG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODI1MjksImV4cCI6MjA1NzM1ODUyOX0.nxVA0mEaQ1MOp-xvbJH5bcybAc1h0ZIlrJyRrWKwq9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);